{
  "openapi": "3.0.0",
  "info": {
    "title": "Veracode Dynamic Flaw API",
    "description": "Replacement for https://analysiscenter.veracode.com/api/5.0/getdynamicflaws.do",
    "version": "v2"
  },
  "servers": [
    {
      "url": "https://api.veracode.com/",
      "description": "Veracode Global Region (default)"
    },
    {
      "url": "https://api.veracode.eu/",
      "description": "Veracode European Region"
    },
    {
      "url": "https://api.veracode.us/",
      "description": "Veracode US Federal Region"
    }
  ],
  "paths": {
    "/appsec/v2/applications/{app_guid}/findings/{issue_id}/dynamic_flaw_info": {
      "get": {
        "operationId": "getDynamicFlawInfo",
        "summary": "Returns information on a specific dynamic flaw.",
        "description": "Returns detailed information about a single dynamic flaw, including the CWE, description, recommendation, and associated HTTP requests.",
        "parameters": [
          {
            "name": "app_guid",
            "in": "path",
            "description": "GUID for the application.",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "issue_id",
            "in": "path",
            "description": "Unique issue ID for the scanned application.",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "You have successfully submitted your request. Flaw information retrieved successfully.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/DynamicFlaw"
                }
              }
            }
          },
          "400": {
            "description": "Invalid request. Verify all the components of your request and, then, try again.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "401": {
            "description": "You are not authorized to perform this action."
          },
          "403": {
            "description": "Access denied. You are not authorized to make this request."
          },
          "500": {
            "description": "Server-side error. Please try again. If the error persists, contact Veracode Technical Support.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          },
          "504": {
            "description": "Request timed out. Please try again. If the error persists, ensure you have set the correct system time and there are no network connection issues.",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Link": {
        "required": [
          "href"
        ],
        "type": "object",
        "properties": {
          "href": {
            "type": "string",
            "description": "Endpoint for the current request."
          },
          "name": {
            "type": "string",
            "description": "Name of the link."
          },
          "templated": {
            "type": "boolean",
            "description": "True if the \"href\" property is a template. Otherwise, False."
          }
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "message": {
            "type": "string",
            "description": "Error message.",
            "readOnly": true
          },
          "code": {
            "type": "string",
            "description": "Error code.",
            "readOnly": true
          },
          "_links": {
            "$ref": "#/components/schemas/Error__links"
          }
        }
      },
      "IssueSummary": {
        "type": "object",
        "properties": {
          "app_guid": {
            "type": "string",
            "description": "GUID for the application.",
            "readOnly": true
          },
          "app_id": {
            "type": "integer",
            "description": "Unique identifier for the application.",
            "format": "int32",
            "readOnly": true
          },
          "build_id": {
            "type": "integer",
            "description": "ID of the build.",
            "format": "int32",
            "readOnly": true
          },
          "issue_id": {
            "type": "integer",
            "description": "Unique identifier for the flaw.",
            "format": "int32",
            "readOnly": true
          },
          "engine_version": {
            "type": "string",
            "description": "Version of the scanner engine that discovered the flaw. Optionally, the value can be an empty string.",
            "readOnly": true
          },
          "cwe_id": {
            "type": "integer",
            "description": "Unique CWE ID for the flaw.",
            "format": "int32"
          },
          "description": {
            "type": "string",
            "description": "Description of the flaw.",
            "readOnly": true
          },
          "recommendation": {
            "type": "string",
            "description": "Recommended process for fixing the flaw.",
            "readOnly": true
          }
        },
        "example": {
          "app_guid": "1234xcc_ffggd4543_4trcf",
          "issue_id": 7,
          "engine_version": "",
          "cwe_id": 526,
          "description": "HTTP response headers often contain information identifying technologies and version numbers that tools or attackers can use to target subsequent attacks. 'Server Microsoft-IIS 7.5' was observed in the server response.",
          "recommendation": "To suppress version information from Apache, set ServerTokens to prod. More information can be found at http://httpd.apache.org/docs/current/mod/core.html#servertokens. For Microsoft IIS versions earlier than 5.1 use Microsoft's URLScan found at http://support.microsoft.com/default.aspx?scid=kb;en-us;307608. For IIS version 5.1 and higher please use UrlScan 3.1 http://www.iis.net/downloads/microsoft/urlscan. For nginx remove the version information by setting \"server_tokens\" to \"off\" in the nginx configuration file. More information can be found at http://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens. For other services or devices, consult documentation to determine how to disable extraneous headers."
        }
      },
      "DynamicFlaw": {
        "type": "object",
        "properties": {
          "issue_summary": {
            "$ref": "#/components/schemas/IssueSummary"
          },
          "dynamic_flaw_info": {
            "$ref": "#/components/schemas/DynamicSpecificFlawInfo"
          },
          "_links": {
            "$ref": "#/components/schemas/Error__links"
          }
        }
      },
      "DynamicSpecificFlawInfo": {
        "type": "object",
        "properties": {
          "request": {
            "$ref": "#/components/schemas/Request"
          },
          "response": {
            "$ref": "#/components/schemas/Response"
          }
        },
        "example": {
          "request": {
            "url": "https://vuln.example.com/forms/bankLoan.aspx?loadAmount=1000000",
            "raw_bytes": "R0VUIC9wbGVhc2VfcHJldGVuZF90aGlzX2lzX2FfcmVhbF9odHRwX3JlcXVlc3QgSFRUUC8xLjEK",
            "secure": true,
            "port": 443,
            "protocol": "HTTP",
            "method": "get",
            "path": "/forms/bankLoad.aspx",
            "uri": "/forms/bankLoan.aspx?loadAmount=1000000",
            "body": "",
            "referer": "https://vuln.example.com/forms/applyNow.html",
            "attack_vectors": [
              {
                "id": 0,
                "name": "Server&#x3a; Microsoft-IIS&#x2f;7.5",
                "type": "HEADER",
                "description": "banner",
                "original_value": "Microsoft-IIS&#x2f;7.5\"",
                "injected_value": ""
              }
            ]
          },
          "response": {
            "raw_bytes": "MjAwIE9LXHJcblNlcnZlcjogU29tZXRoaW5nQ29vbDEuMFxyXG5cclxuPGh0bWw+PGgxPkhlbGxvIFdvcmxkPC9oMT48L2h0bWw+Cg"
          }
        }
      },
      "Request": {
        "type": "object",
        "properties": {
          "url": {
            "type": "string",
            "description": "URL associated with this request."
          },
          "raw_bytes": {
            "type": "string",
            "description": "Base64-encoded raw HTTP request payload.",
            "readOnly": true
          },
          "secure": {
            "type": "boolean",
            "description": "True if this is a secure HTTPS request, false if HTTP.",
            "readOnly": true
          },
          "port": {
            "type": "integer",
            "description": "TCP port to which this request was made.",
            "readOnly": true
          },
          "protocol": {
            "type": "string",
            "description": "Protocol associated with this request. Typically, HTTP.",
            "readOnly": true
          },
          "method": {
            "type": "string",
            "description": "HTTP method of the request (GET, POST, PUT, PATCH, etc.). Can include custom methods.",
            "readOnly": true
          },
          "path": {
            "type": "string",
            "description": "Path of the URL associated with this request. For example, no scheme, hostname, port, or parameter information.",
            "readOnly": true
          },
          "uri": {
            "type": "string",
            "description": "Relative URI associated with this request, not including the host.",
            "readOnly": true
          },
          "body": {
            "type": "string",
            "description": "Body of the request. May be empty.",
            "readOnly": true
          },
          "referer": {
            "type": "string",
            "description": "Referer, from the HTTP header, associated with the request.",
            "readOnly": true
          },
          "attack_vectors": {
            "type": "array",
            "description": "Attack vector parameters associated with this request.",
            "items": {
              "$ref": "#/components/schemas/AttackVector"
            }
          }
        },
        "example": {
          "url": "https://vuln.example.com/forms/bankLoan.aspx?loadAmount=1000000",
          "raw_bytes": "R0VUIC9wbGVhc2VfcHJldGVuZF90aGlzX2lzX2FfcmVhbF9odHRwX3JlcXVlc3QgSFRUUC8xLjEK",
          "secure": true,
          "port": 443,
          "protocol": "HTTP",
          "method": "get",
          "path": "/forms/bankLoad.aspx",
          "uri": "/forms/bankLoan.aspx?loadAmount=1000000",
          "body": "",
          "referer": "https://vuln.example.com/forms/applyNow.html",
          "attack_vectors": [
            {
              "id": 0,
              "name": "Server&#x3a; Microsoft-IIS&#x2f;7.5",
              "type": "HEADER",
              "description": "banner",
              "original_value": "Microsoft-IIS&#x2f;7.5\"",
              "injected_value": ""
            }
          ]
        }
      },
      "AttackVector": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the attack vector parameter.",
            "readOnly": true
          },
          "type": {
            "type": "string",
            "description": "Type of attack vector parameter.",
            "readOnly": true,
            "enum": [
              "QUERY",
              "HEADER",
              "COOKIE",
              "BODY",
              "PATHPARAM"
            ]
          },
          "original_value": {
            "type": "string",
            "description": "Original value of the attack vector.",
            "readOnly": true
          },
          "injected_value": {
            "type": "string",
            "description": "Injected value of the attack vector, after the scan engine has modified it to detect a flaw.",
            "readOnly": true
          }
        },
        "example": {
          "name": "Server&#x3a; Microsoft-IIS&#x2f;7.5",
          "type": "HEADER",
          "description": "banner",
          "original_value": "Microsoft-IIS&#x2f;7.5\"",
          "injected_value": ""
        }
      },
      "Response": {
        "type": "object",
        "properties": {
          "raw_bytes": {
            "type": "string",
            "description": "Base64-encoded raw HTTP response payload.",
            "readOnly": true
          }
        }
      },
      "Error__links": {
        "required": [
          "help"
        ],
        "type": "object",
        "properties": {
          "help": {
            "$ref": "#/components/schemas/Link"
          }
        },
        "readOnly": true
      }
    }
  }
}